In [5]:
#This notebook is about polynomial regression, which is a type of regression analysis that models the relationship between a dependent variable and one or more independent variables as an nth degree polynomial.
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.pipeline import Pipeline

In [6]:
df=pd.read_csv("customersatisfaction.csv")
df.head()

   Unnamed: 0  Customer Satisfaction  Incentive
0           0              -1.282447   1.010513
1           1               0.425298   2.281043
2           2               1.953070   4.415053
3           3               2.625838  10.563600
4           4              -1.426333   0.627365

In [7]:
df.drop("Unnamed: 0", axis=1, inplace=True)
df.head()

   Customer Satisfaction  Incentive
0              -1.282447   1.010513
1               0.425298   2.281043
2               1.953070   4.415053
3               2.625838  10.563600
4              -1.426333   0.627365

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer Satisfaction  100 non-null    float64
 1   Incentive              100 non-null    float64
dtypes: float64(2)
memory usage: 1.7 KB